# Generated by Django 4.1.5 on 2023-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="Book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
