# Generated by Django 4.1.5 on 2023-01-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_comment_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="book",
            new_name="bok",
        ),
    ]
