# Generated by Django 4.1.5 on 2023-01-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_rename_book_comment_bok"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="recommend",
            field=models.BooleanField(default=True),
        ),
    ]
