# Generated by Django 5.1.6 on 2025-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comment_is_active_comment_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bok',
            new_name='book',
        ),
    ]
